import React, { useState } from 'react';
import { HospitalRecommendationItem } from '../../types/emergency';
import { HeartPulse, AlertTriangle, ShieldCheck, CheckCircle2, X } from 'lucide-react';

interface HospitalAssignmentModalProps {
  hospital: HospitalRecommendationItem | null;
  incidentId: string;
  isOverride: boolean;
  onConfirm: (reason: string, department: string) => Promise<void>;
  onClose: () => void;
}

export const HospitalAssignmentModal: React.FC<HospitalAssignmentModalProps> = ({
  hospital,
  incidentId,
  isOverride,
  onConfirm,
  onClose
}) => {
  const [department, setDepartment] = useState('Emergency Trauma Bay');
  const [reason, setReason] = useState(isOverride ? 'Manual operational override selected by Command Center' : 'Recommended primary emergency match');
  const [submitting, setSubmitting] = useState(false);

  if (!hospital) return null;

  const handleConfirm = async () => {
    setSubmitting(true);
    try {
      await onConfirm(reason, department);
      onClose();
    } catch (e) {
      console.error(e);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[1300] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-700/80 rounded-3xl w-full max-w-lg overflow-hidden shadow-2xl">
        <div className="p-6 bg-slate-950 border-b border-slate-800 flex items-start justify-between">
          <div>
            <span className="text-[10px] uppercase font-black tracking-wider text-cyan-400 block mb-1">
              Dispatch Confirmation
            </span>
            <h3 className="text-lg font-black text-white">Assign Emergency Incident</h3>
            <p className="text-xs text-slate-400 mt-0.5">Incident ID: <span className="font-mono text-cyan-300 font-bold">{incidentId}</span></p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-800 text-slate-400 hover:text-white flex items-center justify-center"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-6 space-y-5">
          {/* Target Hospital Card */}
          <div className="bg-slate-800/60 border border-slate-700 p-4 rounded-2xl">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-400">Destination Hospital</span>
              <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                hospital.rank === 1 ? 'bg-amber-500/20 text-amber-300' : 'bg-slate-700 text-slate-300'
              }`}>
                Rank #{hospital.rank}
              </span>
            </div>
            <h4 className="text-base font-black text-white mt-1">{hospital.hospitalName}</h4>
            <p className="text-xs text-slate-400 mt-0.5">{hospital.address}</p>

            <div className="grid grid-cols-3 gap-2 mt-3 pt-3 border-t border-slate-700/60 text-center text-xs">
              <div>
                <span className="text-[10px] text-slate-400 block">Distance</span>
                <span className="font-bold text-white font-mono">{hospital.distanceKm} km</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 block">ETA</span>
                <span className="font-bold text-cyan-400 font-mono">{hospital.etaText}</span>
              </div>
              <div>
                <span className="text-[10px] text-slate-400 block">ICU Free</span>
                <span className="font-bold text-indigo-400 font-mono">{hospital.resourcesSnapshot.icuBedsAvailable} beds</span>
              </div>
            </div>
          </div>

          {/* Override Notice if non-rank 1 */}
          {isOverride && (
            <div className="bg-amber-950/30 border border-amber-800/60 p-3.5 rounded-xl flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
              <div className="text-xs">
                <span className="font-bold text-amber-300 block">Manual Override Selected</span>
                <span className="text-slate-300">
                  This facility is not the #1 recommendation generated by the algorithm. Your selection and justification will be recorded in the official audit trail.
                </span>
              </div>
            </div>
          )}

          {/* Receiving Department */}
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-300">Receiving Department</label>
            <input
              type="text"
              value={department}
              onChange={(e) => setDepartment(e.target.value)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-500 font-medium"
              placeholder="e.g. Emergency Trauma Bay / Level 1 Critical Care"
            />
          </div>

          {/* Assignment Justification */}
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-slate-300">
              {isOverride ? 'Override Justification (Required for Audit)' : 'Assignment Note'}
            </label>
            <textarea
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={2}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-500"
              placeholder="Provide reason for assignment..."
            />
          </div>

          <div className="bg-cyan-950/30 border border-cyan-800/50 p-3 rounded-xl text-xs text-cyan-200 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-cyan-400 flex-shrink-0" />
            <span>Upon confirmation, hospital emergency staff will receive an urgent priority notification.</span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            disabled={submitting}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold rounded-xl text-xs transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleConfirm}
            disabled={submitting}
            className="px-6 py-2.5 bg-gradient-to-r from-red-600 to-rose-600 hover:from-red-500 hover:to-rose-500 text-white font-black rounded-xl text-xs flex items-center gap-2 shadow-lg shadow-red-600/30 transition-all"
          >
            <HeartPulse className="w-4 h-4" />
            <span>{submitting ? 'Dispatching...' : 'Confirm Assignment & Notify'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
