import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, Copy, Check, Lock, Building2, Key, AlertCircle } from 'lucide-react';

interface HospitalCredentialsModalProps {
  isOpen: boolean;
  hospitalId: string;
  hospitalName: string;
  tempPassword: string;
  onClose: () => void;
}

export const HospitalCredentialsModal: React.FC<HospitalCredentialsModalProps> = ({
  isOpen,
  hospitalId,
  hospitalName,
  tempPassword,
  onClose,
}) => {
  const [copiedId, setCopiedId] = useState(false);
  const [copiedPass, setCopiedPass] = useState(false);
  const [copiedAll, setCopiedAll] = useState(false);

  if (!isOpen) return null;

  const handleCopyId = () => {
    navigator.clipboard.writeText(hospitalId);
    setCopiedId(true);
    setTimeout(() => setCopiedId(false), 2000);
  };

  const handleCopyPass = () => {
    navigator.clipboard.writeText(tempPassword);
    setCopiedPass(true);
    setTimeout(() => setCopiedPass(false), 2000);
  };

  const handleCopyAll = () => {
    const text = `Operation Rakshak - Hospital Portal Credentials\nHospital Name: ${hospitalName}\nHospital ID: ${hospitalId}\nTemporary Password: ${tempPassword}\nPortal Login URL: ${window.location.origin}\nNote: First-time login requires creating a permanent password.`;
    navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
      <motion.div
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.95, opacity: 0 }}
        className="w-full max-w-lg bolt-card border border-slate-700 rounded-2xl shadow-2xl overflow-hidden p-6 sm:p-8 text-white"
      >
        <div className="flex items-center space-x-3 mb-6">
          <div className="w-12 h-12 rounded-2xl bg-emerald-950/80 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
            <CheckCircle2 className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-xl font-black text-white tracking-tight">Hospital Registered Successfully</h3>
            <p className="text-xs text-slate-400">Access credentials generated by national dispatch system</p>
          </div>
        </div>

        <div className="space-y-3.5 mb-6">
          <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
            <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1.5 mb-1">
              <Building2 className="w-3.5 h-3.5 text-blue-400" /> Hospital Name
            </span>
            <p className="text-sm font-bold text-white">{hospitalName}</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
            <div className="flex justify-between items-center mb-1">
              <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1.5">
                <Key className="w-3.5 h-3.5 text-blue-400" /> Hospital ID (Login ID)
              </span>
              <button
                onClick={handleCopyId}
                className="text-xs font-bold text-blue-400 hover:text-blue-300 flex items-center gap-1"
              >
                {copiedId ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedId ? 'Copied' : 'Copy'}
              </button>
            </div>
            <p className="text-lg font-mono font-bold text-blue-400 tracking-wider">{hospitalId}</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
            <div className="flex justify-between items-center mb-1">
              <span className="text-[10px] font-bold uppercase text-slate-400 flex items-center gap-1.5">
                <Lock className="w-3.5 h-3.5 text-amber-400" /> Temporary Password
              </span>
              <button
                onClick={handleCopyPass}
                className="text-xs font-bold text-blue-400 hover:text-blue-300 flex items-center gap-1"
              >
                {copiedPass ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedPass ? 'Copied' : 'Copy'}
              </button>
            </div>
            <p className="text-lg font-mono font-bold text-white tracking-wider select-all">{tempPassword}</p>
          </div>

          <div className="p-3.5 rounded-xl bg-amber-950/40 border border-amber-500/40 flex items-start space-x-3">
            <AlertCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
            <div className="text-xs text-slate-300 space-y-0.5">
              <p className="font-bold text-amber-300">Account Status: PENDING ACTIVATION</p>
              <p className="text-[11px] text-slate-400">Hospital trauma staff will enter this temporary password upon first login and establish permanent security keys.</p>
            </div>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={handleCopyAll}
            className="flex-1 py-2.5 px-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 text-xs font-bold flex items-center justify-center gap-2 transition-colors shadow-xs"
          >
            {copiedAll ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copiedAll ? 'Credentials Copied!' : 'Copy All Details'}
          </button>
          <button
            onClick={onClose}
            className="flex-1 py-2.5 px-4 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs shadow-md transition-colors"
          >
            Done & Return to Directory
          </button>
        </div>
      </motion.div>
    </div>
  );
};
